### ISSUE TITLE
[MenuItem] styles when disabled

### ISSUE THREAD

**Issue by Frumcheg** [skbkontur/retail-ui#141]
Когда MenuItem имеет состояние disabled, он получает соответствующий стиль, который переопределяет основной и элемент выглядит ок.
Но, если есть глобальный стиль для всех ссылок 😱:
```css
a:hover {
  color: paleblue;
}
```
То MenuItem будет реагировать на ховер, ибо он - ссылка.
