### ISSUE TITLE
[Toast] едет верстка c box-sizing: border-box

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#2405]
При наличии на странице стилей:
``` css
* {
    box-sizing: border-box;
}
```

Пропадает крестик:

![image](https://user-images.githubusercontent.com/4607770/119085255-d0ceda80-ba1c-11eb-988e-d1472ecc1b0c.png)
