### ISSUE TITLE
[Button] :active стили в состоянии :disabled IF-621

### ISSUE THREAD

**Issue by Eazymov** [skbkontur/retail-ui#2951]
@skbkontur/react-ui@4.2.0
Chrome@103.0.5060.114 / Edge@103.0.1264.62
Ubuntu@22.04 / Windows 10

При нажатии на `primary` кнопку, она становится `disabled`, но сохраняются стили состояния `:active`.
[Codesandbox](https://codesandbox.io/s/determined-thompson-7yw3gy?file=/src/App.js)
![image](https://user-images.githubusercontent.com/26853518/179731405-de48fb3b-b399-40da-97e3-d06373add463.png)
Судя по всему, баг в браузерах webkit, но легко решается со стороны библиотеки, надо только явно распространить `:disabled` стили на состояния `:active` и `:active:hover`.
Например, проблема в sandbox решается, если добавить в css следующие стили:
```css
button[data-tid="Button__root"]:disabled:hover,
button[data-tid="Button__root"]:disabled:active {
  box-shadow: 0 0 0 1px rgb(0, 0, 0, 0.05);
  background-color: #f6f6f6;
}
```
В то же время замена селектора `.Button:active, .Button:active:hover` на селектор `.Button:enabled:active, .Button:enabled:active:hover` не решает проблему.
