### ISSUE TITLE
[Input] В IE плейсхолдер наезжает на картинку слева

### ISSUE THREAD

**Issue by etulo** [skbkontur/retail-ui#731]
В IE плейсхолдер поля ввода наезжает на иконку слева:
![image](https://user-images.githubusercontent.com/3175930/45798180-401b2c00-bcc2-11e8-8ce3-651d83a2ed63.png)

Проблема актуальна для flat-стиля.

Похоже, аналогично [стилю](https://github.com/skbkontur/retail-ui/blob/bbeafd9ae6a1edc915251ee29404b32ddef8212d/packages/retail-ui/components/Input/Input.flat.less#L202) для иконки справа:
```scss
  .padRight .placeholder {
    right: @side-padding-padded + 1;
  }
```

необходимо добавить стиль для иконки слева:
```scss
  .padLeft .placeholder {
    left: @side-padding-padded + 1;
  }
```

```
- библиотека retail-ui;
- версия 0.23.0.
```
