### ISSUE TITLE
[Modal] Убрать браузерный бордер у крестика при фокусе в Firefox

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#993]
![screenshot 2018-12-12 at 14 44 43](https://user-images.githubusercontent.com/6397708/49860785-50075f80-fe1c-11e8-8a37-05538faf4572.png)

Для кнопки добавляется стиль, который убирает нативный бордер. Тоже самое надо сделать для крестика в модалке.

```css
::-moz-focus-inner {
    border: 0;
    padding: 0;
}
```
